### ISSUE TITLE
add hash to file name

### ISSUE THREAD

**Issue by at15** [at15/assets-bower-ci#10]
In order to prevent browser from caching outdated assets, there are some methods

One common methods is to add hash tag after request url

eg: `common.css?hash=asdasdasd `

But this lead to 2 problems.

1. some browsers discard the hash tag.
2. when upload to cdn server, some client will get `a.css` in version 1.0 and `b.css` in version 1.1. because no matter what the hash tag is, the static server just look at the name, and you can't finish
upload in a flash.

So a better method is to add the hash tag to assets file name

eg: `common-asdasdasd.css`

1. this is a different file, so it will be reloaded.
2. the new one won't overwrite the old one when they have different content.

Rails already support it and `fis` also support it. `yeoman` also support it maybe... i haven't tried it 
because it has too many things bundled.

For more info, have a look at fouber's blog. (Chinese though...)
https://github.com/fouber/blog

**Comment by at15** [comment]
Reopen this issue because hash tag feature is removed in `v0.4.0`, need to have it back

**Comment by at15** [comment]
@swaylq @arrowrowe  we can add hash to file name and copy to dst even if they are not changed, things like `ueditor` can be handled manually at this time, and abc will start work. I will handle this myself after I have @xsfour working on tongqu's notification.

**Comment by arrowrowe** [comment]
Should we close it now?

**Comment by at15** [comment]
@arrowrowe yeap, I think it's time to add the `deprecated` in project description and read me, point to `tam`, you can do that when u got time.
