### ISSUE TITLE
Lint assets.json

### ISSUE THREAD

**Issue by at15** [at15/assets-bower-ci#25]
Lint the configuration json file. throw error before execute

- [x] name and property not match
```json
"jquery": {
     "name": "jquery2"
}
```

- [x] required lib or group not exists
```json
"act": {
    "libs": ["jquery3", "angularjs4"],
    "groups": ["base2"]
}
```

- [ ] allow user to limit error number. eg: stop when meet first error

**Comment by arrowrowe** [comment]
Let's leave error number things for one day.....
